### ISSUE TITLE
Bug for tags with spaces in them

### ISSUE THREAD

**Issue by Stefany93** [modxcms/Tagger#103]
I used Tagger to make a blog, and it had a bug where when I inputted tags with a space like "green vegetables" it wouldn't list the articles when clicked on the tag. So I had to write a snippet to replace the spaces with dashes "-" in order for Tagger to display the categories correctly. For example "green vegetables" became "green-vegetables" and then it worked just fine.

I am merely reporting the bug in case anyone else uses Tagger and has the same issue. Make sure to replace the spaces with dashes for it to work correctly.

**Comment by theboxer** [comment]
Tagger already replaces spaces, if you're using tags on fromtend with some kind of JS to filter your posts, use alias instead of tag name. The alias is URL friendly as well.
