### ISSUE TITLE
Bug when saving tag in cyrillic

### ISSUE THREAD

**Issue by kwazaro** [modxcms/Tagger#105]
When I create cyrillic (russian) tags on resource edit and save document - modx gets freeze. Something wrong with automatic translit function - it can't create proper alias (slug) for tags. This bug occurs in version 1.9.0. Previous versions of component worked fine.

**Comment by kwazaro** [comment]
Hey, anybody help?

**Comment by Moonbase59** [comment]
Maybe same reason as #109 ?

**Comment by theboxer** [comment]
Should be resolved by #109
