### ISSUE TITLE
Auto alias doesn't use friendly_alias_translit, bad for SEO URLs

### ISSUE THREAD

**Issue by Moonbase59** [modxcms/Tagger#109]
Hi,

would it somehow be possible to make Tagger respect the "friendly_alias_translit" system setting?
Currently it doesn’t and this is quite bad for non-ASCII languages and SEO.
It would be great to have the same functionality throughout MODX!

For instance, when MODX generates a URL alias automatically, it uses "friendly_alias_translit". Thus, using German umlauts like "äöüÄÖÜ" MODX will generate will generate things like

www.example.com/demo/gefuehle (for a page called "Gefühle")
www.example.com/demo/traeume (for a page called "Träume")

whereas Tagger will generate tag URLs like

www.example.com/tag/gefhle (for a tag called "Gefühle")
www.example.com/tag/trume (for a tag called "Träume")

Google likes to index the tags, too, so we get a discrepancy between "gefuehle"/"gefhle" and "traeume"/"trume"—**very bad for SEO**.

We wouldn’t even NEED to transliterate, since Google and others perfectly well handle UTF-8 in an URL’s path. Tagger would still modify the tags to be quite unreadable, sometimes. (Think about languages like Russian, Czech, Armenian …)

Since the transliteration code is already in MODX for a while, I think it should be easy to just use it.

Hint: When trying this out and you don’t have any transliteration tables installed, you could try to input "iconv" (instead of "none") into the field "friendly_alias_translit", if that’s available on the server.

**Thanks for considering—it’ll make Tagger so much more usable for non-ASCII language users!**

**Comment by Moonbase59** [comment]
I just realize that you already use "iconv('UTF-8', 'ASCII//TRANSLIT', $name)"—only it doesn’t work as expected.

Seems that some shared host providers don’t set LC_CTYPE correctly (mine is empty), so iconv can’t do it’s thing as supposed to.

I reckon my suggestion is thus still valid for those cases. If the system can’t do it, let the built-in MODX transliteration do it (even if you need an extra table _sigh_).

**Comment by Moonbase59** [comment]
SOLVED for now (MODX 2.5.7-pl):

1. Under System Settings → core → Lexicon and language, set "locale" to the EXACT locale (LC_ALL) your server uses (mine was "de_DE.UTF-8").

This will allow Tagger to use iconv’s "ASCII//TRANSLIT" correctly.

2. Under System Settings → core → Friendly URL, set "friendly_alias_translit" to "iconv".

This will make the rest of MODX FURL aliases behave the same.

So now, Tags get translated the same as other (URL) aliases.

**Comment by Moonbase59** [comment]
Further investigation showed that above was not true:

modresource.class.php uses:

`      case 'iconv':
                /* if iconv is available, use the built-in transliteration it provides */
                $segment = iconv($mbext ? mb_detect_encoding($segment) : $charset, $charset . '//TRANSLIT//IGNORE', $segment);
                break;
       `
Since "$charset" is usually "UTF-8" it effectively does an iconv UTF-8//TRANSLIT//IGNORE thus generating URL paths like "/demo/gefühle.html" whereas Tagger now generates "/tag/gefuehle" since it uses iconv ASCII//TRANSLIT.

Anyone from the MODX dev team reading this?
I now wonder if Tagger or the modresource.class.php should be changed?
Maybe, apart from "iconv", we should have an extra "iconvascii" to allow for "typable" URLs?

**Comment by Elawphant** [comment]
Transliteration is very bad idea, maybe not in terms of seo (google seems to handle transliterated words), but try to explain your physical user that to access the particular page he needs to use words in his language but with english letters. Very non-intuitive.

**Comment by Moonbase59** [comment]
There’s pros and cons to that. Still I feel each and every part in MODX that somehow generates an URL (or alias) should behave the same way.

**Comment by Moonbase59** [comment]
Maybe a little naïve, I tried to test a change in /core/components/tagger/model/tagger/taggertag.class.php:

```php
    public function cleanAlias($tag) {
        $res = new modResource($this->xpdo);
        //$tag = str_replace('/', '-', $tag);
        //$tag = iconv('UTF-8', 'ASCII//TRANSLIT', $tag);
        if (method_exists($res, 'filterPathSegment')) {
          return modResource::filterPathSegment($this->modx, $tag);
        } else {
          return $res->cleanAlias($tag);
        }
    }
```

Not knowing the MODX internals too well, I maybe made an obvious mistake—any help?

(When clearing out a tag’s alias and updating it with this version, it ends up in an endless "Saving" modal.)

**Comment by inixon** [comment]
+1 Have same issue with Russian letters.

**Comment by Elawphant** [comment]
@Moonbase59 This is Tagger github bugreporting page, If the problem is within modx, the bug needs to be reported there.

**Comment by Moonbase59** [comment]
@Elawphant True but as I said this refers to Tagger—it should use MODX’s "filterPathSegment" instead of inventing it’s own. This is what the core functions are for and helps making the Extras more compatible. :-)

**Comment by Moonbase59** [comment]
@theboxer Thanks for trying to solve this.

How can I install it? There’s no update package available, just copying the assets and core changes over into my system didn’t bring me the extra system settings.

With just the assets and core parts copyied into my live system, it still doesn’t respect what’s set in "friendly_alias_translit": I tried with "none", "iconv" and "german" (I have that installed) but it seemingly still uses the "ASCII//TRANSLIT" (instead of using whatever is specified in "friendly_alias_translit").

Help appreciated.

**Comment by theboxer** [comment]
You have to create the system setting on your own. `tagger.remove_accents_tag` and `tagger. remove_accents_group` and set both to false
