### ISSUE TITLE
[ BUG ] MODX 2.6 - Issue with tag group place "In TVs section"

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/Tagger#114]
# Summary
Since upgrading to MODX 2.6 and using Tagger 1.9.0, my tag groups no longer display on resources in the manager when the tag group "place" is set to "In TVs section".

![screen shot 2017-11-06 at 19 52 48](https://user-images.githubusercontent.com/2373940/32458403-a0f96482-c32c-11e7-90f1-3b9bec93d8c1.png)

# Steps to reproduce

I have tried this on an installation I upgraded from MODX 2.5.8 > 2.6 and a fresh installation of MODX 2.6 on MODX Cloud;

1. Install a blank version of MODX 2.6 and install the latest version of Tagger
2. Create a TV of any type called Test and assign it to the BaseTemplate
3. Go to Tagger > Groups, and create a group called "Group Test", set place option to "In TVs section" and finally set Show for Templates to "1"
4. Go to Tagger > Tags and create a tag of your liking - assign this tag to the group "Group Test"
5. Edit the homepage resource

# Observed behaviour

When you edit the homepage resource, Under TV's tab I can see my Test TV I created in step 2, but can't see Tagger TV

# Expected behaviour

To see the tagger input field with my TV options

# Environment 
MODX 2.6 / Tagger 1.9.0

**Comment by theboxer** [comment]
Not a Tagger issue, but it's in Revo 2.6.0, PR submitted: https://github.com/modxcms/revolution/pull/13683

**Comment by jonleverrier** [comment]
thanks for looking into @theboxer !
