### ISSUE TITLE
Can only select 1 tag when using Combo box

### ISSUE THREAD

**Issue by hugopeek** [modxcms/Tagger#63]
Tag limit is set to 0, setting it to 99 won't help. Allow_blank and allow_type are checked.

I presume it should be possible to select more than 1 tag here? And should something be visible below the combo box, like the tag field? If it is, then I'm not seeing it..

**Comment by TheBoxer** [comment]
If you are using field type "Combobox", than you can select only 1 tag. If you want select more, use tag field

**Comment by hugopeek** [comment]
Ah ok, thanks for the info @TheBoxer!
