### ISSUE TITLE
Sort order of available tags

### ISSUE THREAD

**Issue by pepebe** [modxcms/Tagger#65]
I'm sure there is some logic behind this, but I just can't see it.

![bildschirmfoto 2015-01-29 um 15 34 13](https://cloud.githubusercontent.com/assets/667315/5959215/8e5153d6-a7cc-11e4-93d8-d293373a855f.png)

Can we order them alphabetically?

Cheers

**Comment by soulcreate** [comment]
+1

**Comment by davidpede** [comment]
+1

**Comment by Jako** [comment]
It seems not to be fixed with that. For whatever reason the ExtJS store and the output is sorted different than the connector response.

![screenshot](https://cloud.githubusercontent.com/assets/148371/16374490/f8170c64-3c56-11e6-8c13-90a335047a7f.png)

**Comment by davidpede** [comment]
Same here, tags still not sorted alphabetically. Using MODX 2.5

**Comment by rainbowtiger** [comment]
Why is this still closed? It's not working, as people have mentioned. Using MODX 2.5.

**Comment by pelargo** [comment]
Bonjour et merci pour votre message.
Je suis absent du 20 juillet au 10 août 2016 inclus.
Je ne disposerai que d'un accès limité à ma messagerie.

Bien cordialement,

Christian Grenaudier
Pelargo
216, rue La Fayette
75010 Paris
Tél : 09 51 76 30 30 | Mob : 06 08 10 73 42
