### ISSUE TITLE
Layout/Theme of tags below select list

### ISSUE THREAD

**Issue by pepebe** [modxcms/Tagger#66]
The layout used to distinguish active from inactive tags doesn't feel native to the current revo2.3.x design. 

I can't say what's bothering me or how it should look like, but I'm sure somebody should give it some love.

![bildschirmfoto 2015-01-29 um 15 34 13](https://cloud.githubusercontent.com/assets/667315/5959245/ee26d1a0-a7cc-11e4-9fd3-b0db442d4227.png)

Cheers

**Comment by TheBoxer** [comment]
This is actually UI from 2.3 :) It's same as Auto-Tag TV uses.

**Comment by TheBoxer** [comment]
Here are new styles for 2.3, hope you'll like them :)

![screen shot 2015-02-05 at 14 04 02](https://cloud.githubusercontent.com/assets/845220/6060660/e5688572-ad3f-11e4-9e32-f6c73ff45171.png)
