### ISSUE TITLE
Can't edit tag's group after it is created

### ISSUE THREAD

**Issue by rainbowtiger** [modxcms/Tagger#67]
If I right-click on a tag in the list and select "Update tag", I can edit the Name and Alias, but the Group is grayed out and I can't change it. What gives? I can't edit the group in list view under the group column either. Clicking a group shows a popup double-arrow on the right, but it is grayed out and doesn't do anything.

MODX Revo 2.3.3, Tagger 1.6.0-pl

**Comment by TheBoxer** [comment]
That's desired functionality, greyed out = disabled field.

**Comment by soulcreate** [comment]
+1

**Comment by rainbowtiger** [comment]
Yes, I don't know why this was closed. Are you saying it's "desired" to not be able to edit the group??? That doesn't make sense.

**Comment by soulcreate** [comment]
++ ))

**Comment by rainbowtiger** [comment]
This is still a problem. Why can't we change the group of entered tags???

**Comment by mtalvenheimo** [comment]
I changed the group in database table 'modx_tagger_tags'. Not very handy ofc.
