### ISSUE TITLE
Error on Tag name that contains comma

### ISSUE THREAD

**Issue by blue148** [modxcms/Tagger#69]
Making a tag name that has a comma causes an error on the rendering of the field in the resource. 

example: Tag name - Chimney brush, rod and accessories
Tag alias: chimney-brush

This occurs on the ComboBox setting where the option above is omitted from the options. 

Since the values are comma separated on render, there needs to be a way to escape the name characters on the render, but allow them to display in the rendered combo box.

**Comment by theboxer** [comment]
Comma is in general a delimited for tags, so you can't use comma inside the tag.
