### ISSUE TITLE
Output modifiers don't work on placeholders

### ISSUE THREAD

**Issue by adamwintle** [modxcms/Tagger#73]
Standard [MODX output modifiers](http://rtfm.modx.com/revolution/2.x/making-sites-with-modx/customizing-content/input-and-output-filters-(output-modifiers)), such as `ucfirst` which makes the first letter capitalized, doesn't work with the Tagger placeholders; e.g. [[+tag:ucfirst]]

**Comment by theboxer** [comment]
It works for me without a problem :)
