### ISSUE TITLE
strange behavior with accented (é) tags

### ISSUE THREAD

**Issue by hitodev** [modxcms/Tagger#81]
I added "port parallèle" and "port parallele" tags assigned to a resource :
http://imgur.com/vRY0xhe
saved

the tag "port parallele" is missing in Tagger Tag group :
http://imgur.com/diaObEO

After having reloaded the resource where I assigned "port parallèle" and "port parallele",  "port parallele" has disappeared :
http://imgur.com/RhDfGBz

Here a screenshot with expressions including spaced words as tags -- showing the main problem is " " between words?
http://imgur.com/8so6t8C

**Comment by theboxer** [comment]
This is not Tagger issue, but issue in collation in your mysql table.
