### ISSUE TITLE
[BUG] Bulk actions > Remove Selected Tags

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/Tagger#88]
MODX 2.4.1pl
Tagger 1.7.0pl

---

1. Click on tagger in Components Menu
2. Create some test tags in the Tags Tab
3. Select all the test tags in the grid (manually or my clicking the checkbox left of ID)
4. Go to bulk actions drop down menu and click on remove selected tags
5. Nothing happens

I have to delete the tags manually by right clicking on each test tag in the grid.

**Comment by theboxer** [comment]
This is already fixed in f6088b1122bbd51292cd0da009535cdff5a26b82 and will be included in next release.
