### ISSUE TITLE
[Feature request] Add [[+active]] placeholder to TaggerGetTags tpl

### ISSUE THREAD

**Issue by hugopeek** [modxcms/Tagger#89]
If you have a tag cloud somewhere with all the tags in a group, it would be nice to style the tag that's currently being filtered on different from the rest.

I tried comparing the [[+alias]] to the page's [[*alias]], but that doesn't show the last bit of FURL that's being added by Tagger..

**Comment by hugopeek** [comment]
Ah, already there: #82 
But that's not yet in 1.7.0, right?

**Comment by theboxer** [comment]
no, will be in next release
