### ISSUE TITLE
'In TV Section' not possible if TV section is empty 

### ISSUE THREAD

**Issue by Jako** [modxcms/Tagger#94]
The TV section is not created, if there is no TV assigned to the template and Tagger is the only 'TV'. Tagger has to be moved to a tab in that case. It would be nice, to have the TV section created then.

**Comment by theboxer** [comment]
Sorry, I didn't find a way how to correctly init the TV tab if there are no tvs...

**Comment by theboxer** [comment]
Added a fallback to add those groups to the Tagger tab, so you won't lose the Tagger.
