### ISSUE TITLE
TaggerGetCurrentTag Bug

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/Tagger#95]
`[[!TaggerGetCurrentTag? &groupTpl=`currentGroup`&tagTpl=`@INLINE [[+tag]]`&tagSeparator=`, `]]`

When I browse to a tag page, the tag group name is displayed, but the current tag name is missing (does not output)

**Comment by theboxer** [comment]
Can't reproduce this issue.

**Comment by cottoncreative** [comment]
I was having the same issue but the solution is to use [[+tags]] in the groupTpl chunk/INLINE, for example:
```[[!TaggerGetCurrentTag? &groupTpl=`@INLINE [[+tags]]` &tagTpl=`@INLINE [[+tag]]` &tagSeparator=`, `]]```

How about either including an INLINE version as the example or include the 'currentGroup' chunk in the extra too?
